name: Python code verification pipeline
on: 
  push:
    branches: ["main"]

env:
  PIPELINE_USER: "Supriya"

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    outputs:
      status_message: "${{ steps.set_msg.outputs.CUSTOM_MESSAGE}}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: execute app script
        run: python app.py
      - name: Save test report
        uses: actions/upload-artifact@v4
        with:
          name: test-execution-report-${{ matrix.python-version }}
          path: report.txt

      - name: Generate outputs message
        id: set_msg
        run: echo "CUSTOM_MESSAGE=Pipeline validation checks passed clean!" >> $GITHUB_OUTPUT

  deploy-package:
    runs-on: ubuntu-latest
    needs: my-first-job
    steps:
      - name: Deploy package
        run: echo "The previous job said -> ${{ needs.my-first-job.outputs.status_message }}"