name: Python code verification pipeline
on: [push, workflow_dispatch]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: execute app script
        run: python app.py